#!/usr/bin/env ruby

running = `VBoxManage list runningvms -l`.strip.split(/^Name: /).reject(&:empty?)
name = running.find {|n| n.include?('VRDE property: TCP/Ports  = "10001"')}
name = name.split("\n").first.strip if name

if name
  puts "Current VM on port 10001 is named #{name}.\nDo you want to pause it? [y,n]"
  if gets.strip == 'y'
    puts `VBoxManage controlvm #{name} savestate`
    puts "\n\nFinished!"
  else
    puts "Exiting..."
    exit!
  end
else
  puts "ERROR: No VM running on port 10001!"
  exit!
end
